const data = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry",
    year: 2020,
    price: 25000,
    description: "A reliable and comfortable sedan for everyday use.",
    category: "sedan",
    image: "https://content.toyota.com.ph/uploads/prices/701/002_701_1639107449853_000.jpg",
    rating: {
      rate: 4.5,
      count: 100,
    },
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    year: 2022,
    price: 22000,
    description: "A popular compact car known for its fuel efficiency.",
    category: "sedan",
    image: "https://www.honda.com.tr/assets/img/civic/home-banner.png",
    rating: {
      rate: 4.2,
      count: 85,
    },
  },
  {
    id: 3,
    make: "Ford",
    model: "F-150",
    year: 2021,
    price: 35000,
    description: "A powerful pickup truck for heavy-duty work and towing.",
    category: "pickup",
    image: "https://api.ford-koegler.de/fileadmin/Modellreihe/F150/Lightning/Text-Bild-Ford_F-150_Lariat__Willkommen_in_der_Koenigsklasse-Desktop-2x.jpg",
    rating: {
      rate: 4.8,
      count: 120,
    },
  },
  {
    id: 4,
    make: "Chevrolet",
    model: "Camaro",
    year: 2023,
    price: 40000,
    description: "A sporty muscle car with great performance and style.",
    category: "sport",
    image: "https://www.motortrend.com/uploads/2022/10/17-2023-Chevrolet-Camaro-RS-Exterior.jpg",
    rating: {
      rate: 4.6,
      count: 60,
    },
  },
  {
    id: 5,
    make: "BMW",
    model: "X5",
    year: 2022,
    price: 60000,
    description: "A luxurious SUV with advanced features and comfort.",
    category: "suv",
    image: "https://media.ed.edmunds-media.com/bmw/x5/2021/oem/2021_bmw_x5_4dr-suv_xdrive45e_fq_oem_1_1600.jpg",
    rating: {
      rate: 4.9,
      count: 200,
    },
  },
  {
    id: 6,
    make: "Nissan",
    model: "Altima",
    year: 2021,
    price: 23000,
    description: "A family-friendly midsize sedan with a spacious interior.",
    category: "sedan",
    image: "https://smartcdn.gprod.postmedia.digital/driving/wp-content/uploads/2022/03/MyAltima5-e1651160018126.jpg",
    rating: {
      rate: 4.3,
      count: 150,
    },
  },
  {
    id: 7,
    make: "Jeep",
    model: "Wrangler",
    year: 2023,
    price: 38000,
    description: "An off-road capable SUV with a rugged design.",
    category: "suv",
    image: "https://www.motortrend.com/uploads/2022/08/2023-Jeep-Wrangler-Sahara-front-three-quarter-view-1.jpg",
    rating: {
      rate: 4.7,
      count: 180,
    },
  },
  {
    id: 8,
    make: "Tesla",
    model: "Model 3",
    year: 2022,
    price: 50000,
    description: "An electric sedan with cutting-edge technology.",
    category: "sedan",
    image: "https://www.cumhuriyet.com.tr/Archive/2022/4/8/1923876/kapak_161111.jpg",
    rating: {
      rate: 4.9,
      count: 300,
    },
  },
  {
    id: 9,
    make: "Audi",
    model: "Q5",
    year: 2021,
    price: 55000,
    description: "A premium compact SUV with a comfortable and stylish interior.",
    category: "suv",
    image: "https://example.com/audi-q5.jpg",
    rating: {
      rate: 4.5,
      count: 120,
    },
  },
  {
    id: 10,
    make: "Subaru",
    model: "Outback",
    year: 2022,
    price: 28000,
    description: "A versatile wagon with all-wheel drive for outdoor adventures.",
    category: "wagon",
    image: "https://example.com/subaru-outback.jpg",
    rating: {
      rate: 4.4,
      count: 90,
    },
  },
  {
    id: 11,
    make: "Mercedes-Benz",
    model: "C-Class",
    year: 2023,
    price: 65000,
    description: "A luxury compact car with a prestigious brand image.",
    category: "luxury",
    image: "https://example.com/mercedes-c-class.jpg",
    rating: {
      rate: 4.8,
      count: 250,
    },
  },
  {
    id: 12,
    make: "GMC",
    model: "Sierra",
    year: 2021,
    price: 42000,
    description: "A reliable and capable full-size pickup truck.",
    category: "pickup",
    image: "https://example.com/gmc-sierra.jpg",
    rating: {
      rate: 4.6,
      count: 170,
    },
  },
  {
    id: 13,
    make: "Volvo",
    model: "XC60",
    year: 2022,
    price: 57000,
    description: "A safe and elegant SUV with advanced safety features.",
    category: "suv",
    image: "https://example.com/volvo-xc60.jpg",
    rating: {
      rate: 4.7,
      count: 110,
    },
  },
  {
    id: 14,
    make: "Lexus",
    model: "RX",
    year: 2021,
    price: 54000,
    description: "A premium crossover SUV with a smooth and comfortable ride.",
    category: "suv",
    image: "https://example.com/lexus-rx.jpg",
    rating: {
      rate: 4.5,
      count: 190,
    },
  },
  {
    id: 15,
    make: "Porsche",
    model: "911",
    year: 2023,
    price: 110000,
    description: "An iconic sports car with breathtaking performance.",
    category: "sports",
    image: "https://example.com/porsche-911.jpg",
    rating: {
      rate: 4.9,
      count: 80,
    },
  },
  {
    id: 16,
    make: "Chevrolet",
    model: "Equinox",
    year: 2022,
    price: 30000,
    description: "A compact SUV with good fuel efficiency and practicality.",
    category: "suv",
    image: "https://example.com/chevrolet-equinox.jpg",
    rating: {
      rate: 4.3,
      count: 140,
    },
  },
  
]
export default data;
